name: Trigger auto deployment for start

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/start-AutoDeployTrigger-9e2b005a-8c22-40a7-a75e-330006a01d9f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.START_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.START_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.START_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrywlfvvsjefnjpu.azurecr.io
          registryUsername: ${{ secrets.START_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.START_REGISTRY_PASSWORD }}
          containerAppName: start
          resourceGroup: appspaceexpresssample997b
          imageToBuild: containerregistrywlfvvsjefnjpu.azurecr.io/start:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


